export const cupActionTypes = {
	SET_NEW_TEXT: 'SET_NEW_TEXT',
	SET_NEW_IMAGE: 'SET_NEW_IMAGE',
	SET_NEW_IMAGE_ROW: 'SET_NEW_IMAGE_ROW',
	DELETE_IMAGE: 'DELETE_IMAGE',
	RESET_IMAGES: 'RESET_IMAGES',
	SAVE_PREVIEW_IMAGE: 'SAVE_PREVIEW_IMAGE',
	ADD_POSITION_DATA: 'ADD_POSITION_DATA',
	CHANGE_TEXT_FIELD_OPTIONS: 'CHANGE_TEXT_FIELD_OPTIONS',
};
