export const cupActionTypes = {
	SET_NEW_TEXT: 'SET_NEW_TEXT',
	SET_NEW_IMAGE: 'SET_NEW_IMAGE',
	SET_NEW_IMAGE_ROW: 'SET_NEW_IMAGE_ROW',
	DELETE_IMAGE: 'DELETE_IMAGE',
	RESET_IMAGES: 'RESET_IMAGES',
};
